/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Bill;
import service.BillService;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */
public class BillFrame extends javax.swing.JFrame {
    
   // Đảm bảo bạn đã khai báo biến này ở trên đầu class
private BillService billService;
private DefaultTableModel defaultTableModel;
private TableRowSorter<DefaultTableModel> rowSorter;

public BillFrame() {
        initComponents();
        txtSearchBill.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        filterBill(txtSearchBill.getText());
    }

    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        filterBill(txtSearchBill.getText());
    }

    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        filterBill(txtSearchBill.getText());
    }
});
        billService = new BillService();

        // 1. Khởi tạo Model khóa chỉnh sửa
        defaultTableModel = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        jTable1.setModel(defaultTableModel);

        // 2. Thêm cột
        defaultTableModel.addColumn("Bill ID");
        defaultTableModel.addColumn("Water Meter ID");
        defaultTableModel.addColumn("Billing Period");
        defaultTableModel.addColumn("Issue Date");
        defaultTableModel.addColumn("Due Date");
        defaultTableModel.addColumn("Total Amount");
        defaultTableModel.addColumn("Status");

        // 3. Khởi tạo bộ lọc (RowSorter)
        rowSorter = new javax.swing.table.TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(rowSorter);

        // 4. Căn chỉnh giao diện
        jTable1.setRowHeight(30);
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // 5. Đổ dữ liệu
        setTableData(billService.getAllBills());
    }
    
    private void setTableData(List<Bill> bills) {
        // Xóa sạch hàng cũ
        defaultTableModel.setRowCount(0); 

        for (Bill b : bills) {
            defaultTableModel.addRow(new Object[]{
                b.getBillId(),        // Lấy từ rs.getInt("bill_id")
                b.getMeterId(),       // Lấy từ rs.getInt("meter_id")
                b.getBillingPeriod(), // Lấy từ rs.getString("billing_period")
                b.getIssueDate(),     // Lấy từ rs.getDate("issue_date")
                b.getDueDate(),       // Lấy từ rs.getDate("due_date")
                b.getTotalAmount(),   // Lấy từ rs.getDouble("total_amount")
                b.getStatus()         // Lấy từ rs.getString("status")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearchBill = new javax.swing.JTextField();

        jLabel2.setText("Search:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add ");
        addButton.addActionListener(this::addButtonActionPerformed);

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("BILL PANEL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(addButton)
                                .addGap(179, 179, 179))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(addButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
         // TODO add your handling code here:
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    // Tạo Dialog và truyền true để bật Modal
    AddBillFrame addDialog = new AddBillFrame(parent, true);
    addDialog.setVisible(true);
    setTableData(billService.getAllBills());
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Lấy vị trí dòng đang được chọn trong bảng
    int selectedRow = jTable1.getSelectedRow();
    selectedRow = jTable1.convertRowIndexToModel(selectedRow);


if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select one bill in the table to delete!");
    return;
}

selectedRow = jTable1.convertRowIndexToModel(selectedRow);

int billId = (int) defaultTableModel.getValueAt(selectedRow, 0);

    // 3. Hiển thị hộp thoại xác nhận
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to delete Bill  " + billId + "?", "Confirm delete", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Gọi Service để xóa
            billService.deleteBill(billId);
            javax.swing.JOptionPane.showMessageDialog(this, "Delete Bill succeed!");
            
            // Refresh lại bảng
            setTableData(billService.getAllBills()); 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Can not delete this Bill!\nDetail Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select one bill in the table to update!", "Announcement", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    selectedRow = jTable1.convertRowIndexToModel(selectedRow);
    // 2. Lấy toàn bộ dữ liệu từ dòng được chọn gói vào 1 đối tượng Bill
    model.Bill selectedBill = new model.Bill();
    selectedBill.setBillId((int) defaultTableModel.getValueAt(selectedRow, 0));
    selectedBill.setMeterId((int) defaultTableModel.getValueAt(selectedRow, 1));
selectedBill.setBillingPeriod((String) defaultTableModel.getValueAt(selectedRow, 2));
selectedBill.setIssueDate((java.sql.Date) defaultTableModel.getValueAt(selectedRow, 3));
selectedBill.setDueDate((java.sql.Date) defaultTableModel.getValueAt(selectedRow, 4));
selectedBill.setTotalAmount((double) defaultTableModel.getValueAt(selectedRow, 5));
selectedBill.setStatus((String) defaultTableModel.getValueAt(selectedRow, 6));

    // 3. Mở form AddBillFrame nhưng gọi thêm hàm setBillToUpdate()
    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    AddBillFrame editDialog = new AddBillFrame(parent, true);
    
    // Truyền dữ liệu sang form
    editDialog.setBillToUpdate(selectedBill); 
    editDialog.setVisible(true);

    // 4. Refresh lại bảng sau khi form sửa đóng lại
    setTableData(billService.getAllBills());    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillFrame().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearchBill;
    // End of variables declaration//GEN-END:variables
private void filterBill(String query) {
    if (query.trim().isEmpty()) {
        rowSorter.setRowFilter(null);
    } else {
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0, 1));
    }
}
}
