/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Bill;
import service.BillService;

/**
 *
 * @author ThinkPad
 */
public class BillFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillFrame.class.getName());
    BillService billService;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form BillFrame1
     */
    public BillFrame() {
        initComponents();
        billService = new BillService();

        // Khởi tạo table model, không cho sửa ô trực tiếp
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        // Gán model cho bảng (Lưu ý: jTable1 phải đúng tên biến trong Design)
        jTable1.setModel(defaultTableModel);

        // Thêm các cột cho bảng Hóa đơn
        defaultTableModel.addColumn("Mã HĐ");
        defaultTableModel.addColumn("Mã Đồng Hồ");
        defaultTableModel.addColumn("Kỳ Thu");
        defaultTableModel.addColumn("Ngày Xuất");
        defaultTableModel.addColumn("Hạn Chót");
        defaultTableModel.addColumn("Tổng Tiền");
        defaultTableModel.addColumn("Trạng Thái");
        
        setTableData(billService.getAllBills());
        txtSearchBill.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterBill(txtSearchBill.getText());
            }
        });

       
        setTableData(billService.getAllBills());
    }

    
    private void setTableData(List<Bill> bills) {
        // Xóa sạch hàng cũ
        defaultTableModel.setRowCount(0); 

        for (Bill b : bills) {
            defaultTableModel.addRow(new Object[]{
                b.getBillId(),        // Lấy từ rs.getInt("bill_id")
                b.getMeterId(),       // Lấy từ rs.getInt("meter_id")
                b.getBillingPeriod(), // Lấy từ rs.getString("billing_period")
                b.getIssueDate(),     // Lấy từ rs.getDate("issue_date")
                b.getDueDate(),       // Lấy từ rs.getDate("due_date")
                b.getTotalAmount(),   // Lấy từ rs.getDouble("total_amount")
                b.getStatus()         // Lấy từ rs.getString("status")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearchBill = new javax.swing.JTextField();

        jLabel2.setText("Search:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add ");
        addButton.addActionListener(this::addButtonActionPerformed);

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("BILL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addGap(0, 511, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addButton)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
         // TODO add your handling code here:
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    
    // Tạo Dialog và truyền true để bật Modal
    AddBillFrame addDialog = new AddBillFrame(parent, true);
    addDialog.setVisible(true);
    setTableData(billService.getAllBills());
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Lấy vị trí dòng đang được chọn trong bảng
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn trong bảng để xóa!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Lấy Bill ID từ cột đầu tiên (cột 0) của dòng được chọn
    int billId = (int) jTable1.getValueAt(selectedRow, 0);

    // 3. Hiển thị hộp thoại xác nhận
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa hóa đơn mã " + billId + " không?", "Xác nhận xóa", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Gọi Service để xóa
            billService.deleteBill(billId);
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa hóa đơn thành công!");
            
            // Refresh lại bảng
            setTableData(billService.getAllBills()); 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không thể xóa hóa đơn này!\nChi tiết lỗi: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hóa đơn trong bảng để sửa!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Lấy toàn bộ dữ liệu từ dòng được chọn gói vào 1 đối tượng Bill
    model.Bill selectedBill = new model.Bill();
    selectedBill.setBillId((int) jTable1.getValueAt(selectedRow, 0));
    selectedBill.setMeterId((int) jTable1.getValueAt(selectedRow, 1));
    selectedBill.setBillingPeriod((String) jTable1.getValueAt(selectedRow, 2));
    selectedBill.setIssueDate((java.sql.Date) jTable1.getValueAt(selectedRow, 3));
    selectedBill.setDueDate((java.sql.Date) jTable1.getValueAt(selectedRow, 4));
    selectedBill.setTotalAmount((double) jTable1.getValueAt(selectedRow, 5));
    selectedBill.setStatus((String) jTable1.getValueAt(selectedRow, 6));

    // 3. Mở form AddBillFrame nhưng gọi thêm hàm setBillToUpdate()
    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    AddBillFrame editDialog = new AddBillFrame(parent, true);
    
    // Truyền dữ liệu sang form
    editDialog.setBillToUpdate(selectedBill); 
    editDialog.setVisible(true);

    // 4. Refresh lại bảng sau khi form sửa đóng lại
    setTableData(billService.getAllBills());    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearchBill;
    // End of variables declaration//GEN-END:variables
private void filterBill(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(tr);

        if (query.trim().isEmpty()) {
            tr.setRowFilter(null);
        } else {
            // (?i) : Không phân biệt hoa thường
            // 0, 1 : Chỉ tìm kiếm trong cột index 0 (Mã HĐ) và index 1 (Mã Đồng Hồ)
            tr.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0, 1));
        }
    }
}
