/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ThinkPad
 */
public class DashBoardFrame extends javax.swing.JFrame {

    
    
    
    public void refreshStatistics() {
        try {
            service.CustomerService customerService = new service.CustomerService();
            service.BillService billService = new service.BillService();
            service.PaymentService paymentService = new service.PaymentService();
            service.RequestService requestService = new service.RequestService();
            int totalBills = billService.getTotalBillCount();
            int unpaidBills = billService.getUnpaidBillCount();
            
            // Cập nhật các con số cũ
            jLabel5.setText(String.valueOf(customerService.getCustomerCount()));
            lblTotalBills.setText(String.valueOf(billService.getUnpaidCount()));
            
            // Cập nhật Revenue (Định dạng số tiền có dấu $)
            double revenue = paymentService.getTotalRevenue();
            jLabel6.setText("$" + String.format("%.2f", revenue));
            
            lblTotalBills.setText(totalBills + " Bills Paid");
            lblUnpaidBills.setText(unpaidBills + " Unpaid");
            lblUnpaidBills.setForeground(java.awt.Color.RED);
            
            // Cập nhật Pending Requests
            jLabel8.setText(String.valueOf(requestService.getPendingRequestCount()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashBoardFrame.class.getName());

    /**
     * Creates new form DashBoardFrame1
     */
    public DashBoardFrame() {
        initComponents();
        refreshStatistics();
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
    @Override
    public void windowGainedFocus(java.awt.event.WindowEvent e) {
        // Mỗi khi cửa sổ Dashboard được người dùng click chọn lại, nó sẽ tự update
        
    }
    @Override
    public void windowLostFocus(java.awt.event.WindowEvent e) {}
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalBills = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUnpaidBills = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Pending:");

        jLabel1.setText("Customers: ");

        jLabel2.setText("Revenue:");

        jLabel3.setText("Bills:");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        lblTotalBills.setText("jLabel7");

        jLabel8.setText("jLabel8");

        lblUnpaidBills.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalBills)
                                .addGap(31, 31, 31)
                                .addComponent(lblUnpaidBills))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(56, 56, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalBills)
                    .addComponent(lblUnpaidBills))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashBoardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTotalBills;
    private javax.swing.JLabel lblUnpaidBills;
    // End of variables declaration//GEN-END:variables
}
