/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ThinkPad
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame1
     */
    public MainFrame() {
        initComponents();
    }
    private void showView(javax.swing.JFrame frame) {
    // 1. Xóa toàn bộ những gì đang hiện ở vùng bên phải (mainContent)
    mainContent.removeAll();
    
    // 2. Thiết lập BorderLayout để nội dung mới tràn đầy diện tích
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. LẤY RUỘT: Lấy ContentPane của JFrame con để add vào JPanel chính
    mainContent.add(frame.getContentPane(), java.awt.BorderLayout.CENTER);
    
    // 4. Vẽ lại giao diện
    mainContent.revalidate();
    mainContent.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        waterMeterButton = new javax.swing.JButton();
        usageButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        requestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setText("Dashboard    ");
        dashboardButton.addActionListener(this::dashboardButtonActionPerformed);
        jPanel1.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        customerButton.setText("Customer");
        customerButton.addActionListener(this::customerButtonActionPerformed);
        jPanel1.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 99, -1));

        waterMeterButton.setText("Water Meter ");
        waterMeterButton.addActionListener(this::waterMeterButtonActionPerformed);
        jPanel1.add(waterMeterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 99, -1));

        usageButton.setText("Usage");
        usageButton.addActionListener(this::usageButtonActionPerformed);
        jPanel1.add(usageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 99, -1));

        billButton.setText("Bill");
        billButton.addActionListener(this::billButtonActionPerformed);
        jPanel1.add(billButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 99, -1));

        paymentButton.setText("Payment ");
        paymentButton.addActionListener(this::paymentButtonActionPerformed);
        jPanel1.add(paymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 99, -1));

        requestButton.setText("Request      ");
        requestButton.addActionListener(this::requestButtonActionPerformed);
        jPanel1.add(requestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 99, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaga/Blue-Abstract-Background-For-You.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(222, 222));
        jLabel1.setPreferredSize(new java.awt.Dimension(222, 333));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 370));

        mainContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 330));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed
        // TODO add your handling code here:
        showView(new RequestFrame());
    }//GEN-LAST:event_requestButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
        showView(new BillFrame());
    }//GEN-LAST:event_billButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
        showView(new PaymentFrame());
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        showView(new DashBoardFrame());
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        showView(new CustomerFrame());
    }//GEN-LAST:event_customerButtonActionPerformed

    private void waterMeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterMeterButtonActionPerformed
        // TODO add your handling code here:
        showView(new WaterMeterFrame());

    }//GEN-LAST:event_waterMeterButtonActionPerformed

    private void usageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usageButtonActionPerformed
        // TODO add your handling code here:
        showView(new UsageFrame());
    }//GEN-LAST:event_usageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContent;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton requestButton;
    private javax.swing.JButton usageButton;
    private javax.swing.JButton waterMeterButton;
    // End of variables declaration//GEN-END:variables
}
