/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ThinkPad
 */
import com.formdev.flatlaf.FlatLightLaf;
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame1
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Water Management System Empolyee");
    }
    private void showView(javax.swing.JFrame frame) {
    // 1. Xóa toàn bộ những gì đang hiện ở vùng bên phải (mainContent)
    mainContent.removeAll();
    
    // 2. Thiết lập BorderLayout để nội dung mới tràn đầy diện tích
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. LẤY RUỘT: Lấy ContentPane của JFrame con để add vào JPanel chính
    mainContent.add(frame.getContentPane(), java.awt.BorderLayout.CENTER);
    
    // 4. Vẽ lại giao diện
    mainContent.revalidate();
    mainContent.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        waterMeterButton = new javax.swing.JButton();
        usageButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        requestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(51, 51, 51));
        dashboardButton.setText("Dashboard    ");
        dashboardButton.setAlignmentY(1.0F);
        dashboardButton.setHideActionText(true);
        dashboardButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboardButton.addActionListener(this::dashboardButtonActionPerformed);
        jPanel1.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, -1));

        customerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        customerButton.setForeground(new java.awt.Color(51, 51, 51));
        customerButton.setText("Customer");
        customerButton.setAlignmentY(1.0F);
        customerButton.setHideActionText(true);
        customerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerButton.addActionListener(this::customerButtonActionPerformed);
        jPanel1.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, -1));

        waterMeterButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        waterMeterButton.setForeground(new java.awt.Color(51, 51, 51));
        waterMeterButton.setText("Water Meter ");
        waterMeterButton.setAlignmentY(1.0F);
        waterMeterButton.setHideActionText(true);
        waterMeterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        waterMeterButton.addActionListener(this::waterMeterButtonActionPerformed);
        jPanel1.add(waterMeterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 110, -1));

        usageButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        usageButton.setForeground(new java.awt.Color(51, 51, 51));
        usageButton.setText("Usage");
        usageButton.setAlignmentY(1.0F);
        usageButton.setHideActionText(true);
        usageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usageButton.addActionListener(this::usageButtonActionPerformed);
        jPanel1.add(usageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, -1));

        billButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        billButton.setForeground(new java.awt.Color(51, 51, 51));
        billButton.setText("Bill");
        billButton.setAlignmentY(1.0F);
        billButton.setHideActionText(true);
        billButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        billButton.addActionListener(this::billButtonActionPerformed);
        jPanel1.add(billButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, -1));

        paymentButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(51, 51, 51));
        paymentButton.setText("Payment ");
        paymentButton.setAlignmentY(1.0F);
        paymentButton.setHideActionText(true);
        paymentButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paymentButton.addActionListener(this::paymentButtonActionPerformed);
        jPanel1.add(paymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 110, -1));

        requestButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        requestButton.setForeground(new java.awt.Color(51, 51, 51));
        requestButton.setText("  Request      ");
        requestButton.setAlignmentY(1.0F);
        requestButton.setHideActionText(true);
        requestButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        requestButton.addActionListener(this::requestButtonActionPerformed);
        jPanel1.add(requestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaga/Blue-Abstract-Background-For-You.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(222, 222));
        jLabel1.setPreferredSize(new java.awt.Dimension(222, 333));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        mainContent.setAlignmentY(1.0F);
        mainContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 780, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1021, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed
        // TODO add your handling code here:
        showView(new RequestFrame());
    }//GEN-LAST:event_requestButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
        showView(new BillFrame());
    }//GEN-LAST:event_billButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
        showView(new PaymentFrame());
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        showView(new DashBoardFrame());
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        showView(new CustomerFrame());
    }//GEN-LAST:event_customerButtonActionPerformed

    private void waterMeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterMeterButtonActionPerformed
        // TODO add your handling code here:
        showView(new WaterMeterFrame());

    }//GEN-LAST:event_waterMeterButtonActionPerformed

    private void usageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usageButtonActionPerformed
        // TODO add your handling code here:
        showView(new UsageFrame());
    }//GEN-LAST:event_usageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          try {
        // Sử dụng FlatLightLaf thay vì FlatDarkLaf
        com.formdev.flatlaf.FlatLightLaf.setup();
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, "Không thể tải Light Mode", ex);
    }

    // 2. Chạy ứng dụng
    java.awt.EventQueue.invokeLater(() -> {
        new MainFrame().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billButton;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContent;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton requestButton;
    private javax.swing.JButton usageButton;
    private javax.swing.JButton waterMeterButton;
    // End of variables declaration//GEN-END:variables
}
