/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Payment;
import service.PaymentService;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author ThinkPad
 */
public class PaymentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentFrame.class.getName());
    PaymentService paymentService;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form PaymentFrame1
     */
    public PaymentFrame() {
        initComponents();
        paymentService = new PaymentService();
        
        tb1Payment.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                // Lấy text từ chính ô JTextField đang gõ
                String query = tb1Payment.getText();
                filterPayment(query);
            }});
        
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa trực tiếp trên table
            }
        };

        jTable1.setModel(defaultTableModel);

        // Thêm các cột cho bảng Thanh toán
        defaultTableModel.addColumn("Payment ID");
        defaultTableModel.addColumn("Bill ID");
        defaultTableModel.addColumn("Payment Date");
        defaultTableModel.addColumn("Amount");
        defaultTableModel.addColumn("Payment Method");

        // Đổ dữ liệu từ Service vào
        setTableData(paymentService.getAllPayments());
    }
    private void setTableData(List<Payment> payments) {
        defaultTableModel.setRowCount(0); // Xóa trắng bảng trước khi nạp

        for (Payment p : payments) {
            defaultTableModel.addRow(new Object[]{
                p.getPaymentId(),
                p.getBillId(),
                p.getPaymentDate(),
                p.getAmount(),
                p.getPaymentMethod()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb1Payment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("PAYMENT PANEL");

        jLabel2.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tb1Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tb1Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(addButton)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
     java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    
    
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    
    AddPayment addDialog = new AddPayment(parentFrame, true);
    
    
    addDialog.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row to update!");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        int billId = Integer.parseInt(jTable1.getValueAt(selectedRow, 1).toString());
        String date = jTable1.getValueAt(selectedRow, 2).toString();
        double amount = Double.parseDouble(jTable1.getValueAt(selectedRow, 3).toString());
        String method = jTable1.getValueAt(selectedRow, 4).toString();

        UpdatePaymentFrame updateFrame = new UpdatePaymentFrame();
        updateFrame.setPaymentData(id, billId, date, amount, method);
        updateFrame.setVisible(true);
        
        updateFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setTableData(paymentService.getAllPayments()); // Refresh bảng
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a row to delte!");
            return;
        }

        if (javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
            paymentService.deletePayment(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Deleted!");
            setTableData(paymentService.getAllPayments()); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tb1Payment;
    // End of variables declaration//GEN-END:variables
private void filterPayment(String query) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(sorter);

        if (query == null || query.trim().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            // (?i): Không phân biệt hoa thường
            // 0, 1: Chỉ lọc dữ liệu tại cột index 0 và index 1
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + query, 0, 1));
        }
    }
}
