/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Request;
import service.RequestService;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/**
 *
 * @author ThinkPad
 */
public class RequestFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RequestFrame.class.getName());
    RequestService requestService;
    DefaultTableModel defaultTableModel;
    private TableRowSorter<DefaultTableModel> rowSorter;
    /**
     * Creates new form RequestFrame1
     */
    
    public RequestFrame() {
    initComponents();

    requestService = new RequestService();

    // 1. Model không cho edit
    defaultTableModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    jTable1.setModel(defaultTableModel);

    // 2. Thêm cột
    defaultTableModel.addColumn("ID");
    defaultTableModel.addColumn("Customer ID");
    defaultTableModel.addColumn("Employee ID");
    defaultTableModel.addColumn("Request Type");
    defaultTableModel.addColumn("Description");
    defaultTableModel.addColumn("Status");
    defaultTableModel.addColumn("Created Date");
    defaultTableModel.addColumn("Processed Date");

    // 3. RowSorter (giống Bill)
    rowSorter = new TableRowSorter<>(defaultTableModel);
    jTable1.setRowSorter(rowSorter);

    // 4. Căn giữa table
    jTable1.setRowHeight(30);

    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // 5. Load dữ liệu
    setTableData(requestService.getAllRequests());

    // 6. Search realtime (DocumentListener)
    txtSearchPayment.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterRequest(txtSearchPayment.getText());
        }

        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterRequest(txtSearchPayment.getText());
        }

        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterRequest(txtSearchPayment.getText());
        }
    });
}
    private void setTableData(List<Request> requests) {
        defaultTableModel.setRowCount(0); // Xóa dữ liệu cũ

        for (Request r : requests) {
            defaultTableModel.addRow(new Object[]{
                r.getRequestId(),
                r.getCustomerId(),
                r.getEmployeeId() == null ? "No employee Avaible" : r.getEmployeeId(), // Xử lý nếu nhân viên NULL
                r.getRequestType(),
                r.getDescription(),
                r.getStatus(),
                r.getDateCreated(),
                r.getDateResolved() == null ? "Waiting" : r.getDateResolved()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchPayment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("REQUEST PANEL");

        jLabel2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearchPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addButton)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // Khởi tạo và ép Modal bằng tham số 'true'
    AddRequestFrame addDialog = new AddRequestFrame(parentFrame, true);
    
    // Hiển thị - Lúc này người dùng không thể bấm ra ngoài cho đến khi đóng form này
    addDialog.setVisible(true);
    setTableData(requestService.getAllRequests());
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select 1 row to update!");
            return;
        }

      

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Select 1 row to update!");
    return;
}

// FIX lệch index
selectedRow = jTable1.convertRowIndexToModel(selectedRow);

int id = (int) defaultTableModel.getValueAt(selectedRow, 0);
String empId = defaultTableModel.getValueAt(selectedRow, 2).toString();
String type = defaultTableModel.getValueAt(selectedRow, 3).toString();
String desc = defaultTableModel.getValueAt(selectedRow, 4).toString();
String status = defaultTableModel.getValueAt(selectedRow, 5).toString();

        UpdateRequestFrame updateFrame = new UpdateRequestFrame();
        updateFrame.setRequestData(id, type, desc, status, empId);
        updateFrame.setVisible(true);
        
        updateFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setTableData(requestService.getAllRequests()); 
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select this row to delete!");
            return;
        }

        if (javax.swing.JOptionPane.showConfirmDialog(this, "Delete this request?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION) {
           

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Select this row to delete!");
    return;
}

// FIX lệch index
selectedRow = jTable1.convertRowIndexToModel(selectedRow);

int id = (int) defaultTableModel.getValueAt(selectedRow, 0);

if (JOptionPane.showConfirmDialog(this, "Delete this request?", "Confirm", JOptionPane.YES_NO_OPTION)
        == JOptionPane.YES_OPTION) {

    requestService.deleteRequest(id);
    setTableData(requestService.getAllRequests());
}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RequestFrame().setVisible(true));
    }
    private void filterRequest(String query) {
    if (query.trim().isEmpty()) {
        rowSorter.setRowFilter(null);
    } else {
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0, 1, 3, 5));
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearchPayment;
    // End of variables declaration//GEN-END:variables
}
