/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Request;
import service.RequestService;

/**
 *
 * @author ThinkPad
 */
public class RequestFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RequestFrame.class.getName());
    RequestService requestService;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form RequestFrame1
     */
    public RequestFrame() {
        initComponents();
        requestService = new RequestService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa trực tiếp trên bảng
            }
        };

        jTable1.setModel(defaultTableModel);

        
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Mã KH");
        defaultTableModel.addColumn("Mã NV");
        defaultTableModel.addColumn("Loại yêu cầu");
        defaultTableModel.addColumn("Mô tả");
        defaultTableModel.addColumn("Trạng thái");
        defaultTableModel.addColumn("Ngày tạo");
        defaultTableModel.addColumn("Ngày xử lý");

       
        setTableData(requestService.getAllRequests());
    }
    private void setTableData(List<Request> requests) {
        defaultTableModel.setRowCount(0); // Xóa dữ liệu cũ

        for (Request r : requests) {
            defaultTableModel.addRow(new Object[]{
                r.getRequestId(),
                r.getCustomerId(),
                r.getEmployeeId() == null ? "Chưa có" : r.getEmployeeId(), // Xử lý nếu nhân viên NULL
                r.getRequestType(),
                r.getDescription(),
                r.getStatus(),
                r.getDateCreated(),
                r.getDateResolved() == null ? "Đang chờ" : r.getDateResolved()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        jLabel1.setText("REQUEST PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(addButton)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // Khởi tạo và ép Modal bằng tham số 'true'
    AddRequestFrame addDialog = new AddRequestFrame(parentFrame, true);
    
    // Hiển thị - Lúc này người dùng không thể bấm ra ngoài cho đến khi đóng form này
    addDialog.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Chọn một dòng để sửa!");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String empId = jTable1.getValueAt(selectedRow, 2).toString();
        String type = jTable1.getValueAt(selectedRow, 3).toString();
        String desc = jTable1.getValueAt(selectedRow, 4).toString();
        String status = jTable1.getValueAt(selectedRow, 5).toString();

        UpdateRequestFrame updateFrame = new UpdateRequestFrame();
        updateFrame.setRequestData(id, type, desc, status, empId);
        updateFrame.setVisible(true);
        
        updateFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setTableData(requestService.getAllRequests()); 
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Chọn dòng để xóa!");
            return;
        }

        if (javax.swing.JOptionPane.showConfirmDialog(this, "Xóa yêu cầu này?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
            requestService.deleteRequest(id);
            setTableData(requestService.getAllRequests()); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RequestFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
