/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import model.WaterUsage;
import service.UsageService;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
/**
 *
 * @author ThinkPad
 */
public class UsageFrame extends javax.swing.JFrame {
    UsageService usageService; 
    DefaultTableModel defaultTableModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsageFrame.class.getName());

    /**
     * Creates new form UsageFrame
     */
    public UsageFrame() {
        initComponents();
        usageService = new UsageService(); 
        
        txtSearch.setText("");

        // 2. Gắn sự kiện tìm kiếm
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterUsage(txtSearch.getText());
            }
        });

        // 3. Khởi tạo Model cho bảng và khóa không cho sửa trực tiếp
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(defaultTableModel);

        defaultTableModel.addColumn("Usage ID");
        defaultTableModel.addColumn("Water Meter ID");
        defaultTableModel.addColumn("Instaltion Date");
        defaultTableModel.addColumn("Previous Reading");
        defaultTableModel.addColumn("Current Reading");
        defaultTableModel.addColumn("Consumption");

        
        setTableData(usageService.getAllUsage());
    }
    private void setTableData(List<WaterUsage> usages) {
        defaultTableModel.setRowCount(0);

        for (WaterUsage u : usages) { 
            double consumption = u.getCurrentReading() - u.getPreviousReading();
            defaultTableModel.addRow(new Object[]{
                u.getUsageId(),
                u.getMeterId(),
                u.getReadingDate(),
                u.getPreviousReading(),
                u.getCurrentReading(),
                consumption
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("USAGE PANEL");

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Update");

        jButton3.setText("ADD");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // 2. Gọi Dialog với tham số 'true' để khóa màn hình chính
    AddUsageFrame addDialog = new AddUsageFrame(parentFrame, true, usageService);
    // 3. Hiển thị
    addDialog.setVisible(true);
    // Refresh table after dialog closed
    setTableData(usageService.getAllUsage());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a usage to update.");
            return;
        }

        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        // find usage by id
        WaterUsage found = null;
        for (WaterUsage u : usageService.getAllUsage()) {
            if (u.getUsageId() == id) {
                found = u;
                break;
            }
        }

        if (found == null) {
            JOptionPane.showMessageDialog(this, "Selected usage not found.");
            return;
        }

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) parentFrame = (java.awt.Frame) parentWindow;

        AddUsageFrame editDialog = new AddUsageFrame(parentFrame, true, usageService, found);
        editDialog.setVisible(true);
        setTableData(usageService.getAllUsage());
    }

    private void jButton1ActionPerformedDelete(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a usage to delete.");
            return;
        }
        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        int confirm = JOptionPane.showConfirmDialog(this, "Delete selected usage?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        usageService.deleteUsage(id);
        setTableData(usageService.getAllUsage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsageFrame().setVisible(true));
    }
    private void filterUsage(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(tr);

        if (query.trim().length() == 0) {
            tr.setRowFilter(null);
        } else {
            // Tham số thứ 2 là index của các cột muốn lọc. 
            // Ở đây là cột 0 (Mã sử dụng) và cột 1 (Mã đồng hồ)
            tr.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0, 1));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
}
