/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import model.WaterUsage;
import service.UsageService;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
/**
 *
 * @author ThinkPad
 */
public class UsageFrame extends javax.swing.JFrame {
    UsageService usageService; 
    DefaultTableModel defaultTableModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsageFrame.class.getName());

    /**
     * Creates new form UsageFrame
     */
    private TableRowSorter<DefaultTableModel> rowSorter;
   public UsageFrame() {
    initComponents();
    usageService = new UsageService(); 

    // 1. Khởi tạo Model và khóa chỉnh sửa trực tiếp
    defaultTableModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    jTable1.setModel(defaultTableModel);

    // 2. Thêm các cột (Thêm đầy đủ trước khi chỉnh giao diện)
    defaultTableModel.addColumn("Usage ID");
    defaultTableModel.addColumn("Water Meter ID");
    defaultTableModel.addColumn("Reading Date"); // Đổi Instaltion Date thành Reading Date cho đúng logic sử dụng
    defaultTableModel.addColumn("Previous");
    defaultTableModel.addColumn("Current");
    defaultTableModel.addColumn("Consumption");

    // 3. Thiết lập RowSorter để tìm kiếm
    rowSorter = new javax.swing.table.TableRowSorter<>(defaultTableModel);
    jTable1.setRowSorter(rowSorter);

    // --- KHỐI QUẢN LÝ GIAO DIỆN BẢNG (Đồng bộ hệ thống) ---

    // A. Căn giữa toàn bộ nội dung hàng
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // B. Cấu hình độ rộng cột (Sử dụng setMinWidth để hiện đủ chữ tiêu đề)
    jTable1.getColumnModel().getColumn(0).setMinWidth(80);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);  // Usage ID

    jTable1.getColumnModel().getColumn(1).setMinWidth(110);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(110); // Water Meter ID

    jTable1.getColumnModel().getColumn(2).setMinWidth(120);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(120); // Reading Date

    jTable1.getColumnModel().getColumn(3).setMinWidth(110);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(110); // Previous

    jTable1.getColumnModel().getColumn(4).setMinWidth(100);
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(100); // Current

    jTable1.getColumnModel().getColumn(5).setMinWidth(110);
    jTable1.getColumnModel().getColumn(5).setPreferredWidth(110); // Consumption

    // C. Căn giữa tiêu đề bảng (Header)
    if (jTable1.getTableHeader().getDefaultRenderer() instanceof javax.swing.table.DefaultTableCellRenderer) {
        ((javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }

    // D. Tăng chiều cao hàng (Đồng bộ 30px)
    jTable1.setRowHeight(30);

    // --- KẾT THÚC KHỐI QUẢN LÝ ---

    // 4. Đổ dữ liệu và gắn sự kiện tìm kiếm
    setTableData(usageService.getAllUsage());
    
    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            String text = txtSearch.getText();
            if (text.trim().isEmpty()) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
            }
        }
    });
}
    private void setTableData(List<WaterUsage> usages) {
        defaultTableModel.setRowCount(0);

        for (WaterUsage u : usages) { 
            double consumption = u.getCurrentReading() - u.getPreviousReading();
            defaultTableModel.addRow(new Object[]{
                u.getUsageId(),
                u.getMeterId(),
                u.getReadingDate(),
                u.getPreviousReading(),
                u.getCurrentReading(),
                consumption
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("USAGE PANEL");

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Update");

        jButton3.setText("ADD");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // 2. Gọi Dialog với tham số 'true' để khóa màn hình chính
    AddUsageFrame addDialog = new AddUsageFrame(parentFrame, true, usageService);
    // 3. Hiển thị
    addDialog.setVisible(true);
    // Refresh table after dialog closed
    setTableData(usageService.getAllUsage());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a usage to update.");
            return;
        }

        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        // find usage by id
        WaterUsage found = null;
        for (WaterUsage u : usageService.getAllUsage()) {
            if (u.getUsageId() == id) {
                found = u;
                break;
            }
        }

        if (found == null) {
            JOptionPane.showMessageDialog(this, "Selected usage not found.");
            return;
        }

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) parentFrame = (java.awt.Frame) parentWindow;

        AddUsageFrame editDialog = new AddUsageFrame(parentFrame, true, usageService, found);
        editDialog.setVisible(true);
        setTableData(usageService.getAllUsage());
    }

    private void jButton1ActionPerformedDelete(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a usage to delete.");
            return;
        }
        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        int confirm = JOptionPane.showConfirmDialog(this, "Delete selected usage?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        usageService.deleteUsage(id);
        setTableData(usageService.getAllUsage());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsageFrame().setVisible(true));
    }
    private void filterUsage(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(tr);

        if (query.trim().length() == 0) {
            tr.setRowFilter(null);
        } else {
            // Tham số thứ 2 là index của các cột muốn lọc. 
            // Ở đây là cột 0 (Mã sử dụng) và cột 1 (Mã đồng hồ)
            tr.setRowFilter(RowFilter.regexFilter("(?i)" + query, 0, 1));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
}
