/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.WaterMeter;
import service.WaterMeterService;

/**
 *
 * @author ThinkPad
 */
public class WaterMeterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WaterMeterFrame.class.getName());
    WaterMeterService waterMeterService;
    DefaultTableModel defaultTableModel;
    private javax.swing.table.TableRowSorter<DefaultTableModel> rowSorter; // <--- THÊM DÒNG NÀY
    /**
     * Creates new form WaterMeterFrame1
     */
    public WaterMeterFrame() {
    initComponents();
    waterMeterService = new WaterMeterService();

    // 1. Khởi tạo Model và khóa chỉnh sửa ô
    defaultTableModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    jTable1.setModel(defaultTableModel);

    // 2. Thêm các cột (Phải thêm trước khi chỉnh độ rộng)
    defaultTableModel.addColumn("Water Meter ID");
    defaultTableModel.addColumn("Customer ID");
    defaultTableModel.addColumn("Installation Day"); // Sửa lỗi chính tả "Instaltion" thành "Installation"
    defaultTableModel.addColumn("Type");
    defaultTableModel.addColumn("Status");
    
    // 3. Thiết lập RowSorter để tìm kiếm
    rowSorter = new javax.swing.table.TableRowSorter<>(defaultTableModel);
    jTable1.setRowSorter(rowSorter);

    // --- KHỐI QUẢN LÝ GIAO DIỆN BẢNG (Đồng bộ với CustomerFrame) ---

    // A. Căn giữa toàn bộ các hàng
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // B. Cấu hình độ rộng cột thông minh (Dùng setMinWidth để không bị che chữ)
    // Cột 0: Water Meter ID
    jTable1.getColumnModel().getColumn(0).setMinWidth(120);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);

    // Cột 1: Customer ID
    jTable1.getColumnModel().getColumn(1).setMinWidth(100);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);

    // Cột 2: Installation Day
    jTable1.getColumnModel().getColumn(2).setMinWidth(130);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);

    // Cột 3: Type
    jTable1.getColumnModel().getColumn(3).setMinWidth(100);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);

    // Cột 4: Status
    jTable1.getColumnModel().getColumn(4).setMinWidth(100);
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);

    // C. Căn giữa tiêu đề bảng (Header)
    if (jTable1.getTableHeader().getDefaultRenderer() instanceof javax.swing.table.DefaultTableCellRenderer) {
        ((javax.swing.table.DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }

    // D. Tăng chiều cao hàng cho hiện đại
    jTable1.setRowHeight(30);

    // --- KẾT THÚC KHỐI QUẢN LÝ ---

    // 4. Đổ dữ liệu lên bảng
    setTableData(waterMeterService.getAllMeter());
}
    private void setTableData(List<WaterMeter> meters) {
        defaultTableModel.setRowCount(0); // Xóa dữ liệu cũ trên bảng

        for (WaterMeter m : meters) {
            defaultTableModel.addRow(new Object[]{
                m.getMeterId(),
                m.getCustomerId(),
                m.getInstallationDate(),
                m.getMeterType(),
                m.getStatus()
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("WATER METER PANEL");

        jLabel2.setText("Search:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addGap(145, 145, 145)))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(addButton)
                    .addComponent(jButton1))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // 2. Tạo JDialog với tham số true (Modal)
    AddWaterMeterFrame addDialog = new AddWaterMeterFrame(parentFrame, true, waterMeterService);
    
    // 3. Hiển thị (Lúc này MainFrame sẽ bị khóa)
    addDialog.setVisible(true);
    setTableData(waterMeterService.getAllMeter());
    }//GEN-LAST:event_addButtonActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText().trim();
        
        if (text.length() == 0) {
            rowSorter.setRowFilter(null); // Không gõ gì thì hiện tất cả
        } else {
            // Số 0 và 1 ở cuối là bí quyết: Nó bảo Java CHỈ tìm trong cột 0 (Mã đồng hồ) và cột 1 (Mã KH)
            rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text, 0, 1));
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateButtonActionPerformed(evt);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deleteButtonActionPerformed(evt);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a meter to update.");
            return;
        }

        int modelRow = jTable1.convertRowIndexToModel(row);
        
        Object idObj = defaultTableModel.getValueAt(modelRow, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        WaterMeter found = null;
        for (WaterMeter m : waterMeterService.getAllMeter()) {
            if (m.getMeterId() == id) { found = m; break; }
        }

        if (found == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected meter not found.");
            return;
        }

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) parentFrame = (java.awt.Frame) parentWindow;

        AddWaterMeterFrame editDialog = new AddWaterMeterFrame(parentFrame, true, waterMeterService, found);
        editDialog.setVisible(true);
        setTableData(waterMeterService.getAllMeter());
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a meter to delete.");
            return;
        }
        int modelRow = jTable1.convertRowIndexToModel(row);
        
        Object idObj = defaultTableModel.getValueAt(modelRow, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete selected meter?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        waterMeterService.deleteMeter(id);
        setTableData(waterMeterService.getAllMeter());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WaterMeterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
