/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.WaterMeter;
import service.WaterMeterService;

/**
 *
 * @author ThinkPad
 */
public class WaterMeterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WaterMeterFrame.class.getName());
    WaterMeterService waterMeterService;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form WaterMeterFrame1
     */
    public WaterMeterFrame() {
        initComponents();
        waterMeterService = new WaterMeterService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Khóa không cho sửa trực tiếp trên bảng
            }
        };

        jTable1.setModel(defaultTableModel);

        // Định nghĩa các cột cho bảng Đồng hồ nước
        defaultTableModel.addColumn("Mã đồng hồ");
        defaultTableModel.addColumn("Mã khách hàng");
        defaultTableModel.addColumn("Ngày lắp đặt");
        defaultTableModel.addColumn("Loại đồng hồ");
        defaultTableModel.addColumn("Trạng thái");

        // Gọi hàm đổ dữ liệu
        setTableData(waterMeterService.getAllMeter());
    }
    private void setTableData(List<WaterMeter> meters) {
        defaultTableModel.setRowCount(0); // Xóa dữ liệu cũ trên bảng

        for (WaterMeter m : meters) {
            defaultTableModel.addRow(new Object[]{
                m.getMeterId(),
                m.getCustomerId(),
                m.getInstallationDate(),
                m.getMeterType(),
                m.getStatus()
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");

        jButton2.setText("Delete");

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);
        jButton1.addActionListener(this::updateButtonActionPerformed);
        jButton2.addActionListener(this::deleteButtonActionPerformed);

        jLabel1.setText("REQUEST PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(addButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(addButton)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    java.awt.Frame parentFrame = null;
    if (parentWindow instanceof java.awt.Frame) {
        parentFrame = (java.awt.Frame) parentWindow;
    }

    // 2. Tạo JDialog với tham số true (Modal)
    AddWaterMeterFrame addDialog = new AddWaterMeterFrame(parentFrame, true, waterMeterService);
    
    // 3. Hiển thị (Lúc này MainFrame sẽ bị khóa)
    addDialog.setVisible(true);
    setTableData(waterMeterService.getAllMeter());
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a meter to update.");
            return;
        }

        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        WaterMeter found = null;
        for (WaterMeter m : waterMeterService.getAllMeter()) {
            if (m.getMeterId() == id) { found = m; break; }
        }

        if (found == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected meter not found.");
            return;
        }

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) parentFrame = (java.awt.Frame) parentWindow;

        AddWaterMeterFrame editDialog = new AddWaterMeterFrame(parentFrame, true, waterMeterService, found);
        editDialog.setVisible(true);
        setTableData(waterMeterService.getAllMeter());
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a meter to delete.");
            return;
        }
        Object idObj = defaultTableModel.getValueAt(row, 0);
        int id = Integer.parseInt(String.valueOf(idObj));

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete selected meter?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        waterMeterService.deleteMeter(id);
        setTableData(waterMeterService.getAllMeter());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WaterMeterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
