/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import model.Customer;
import javax.swing.table.DefaultTableModel;
import service.CustomerService;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ThinkPad
 */
public class CustomerFrame extends javax.swing.JFrame {

    // Khai báo biến
    CustomerService customerService;
    DefaultTableModel defaultTableModel;
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> rowSorter;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerFrame.class.getName());

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents(); // Phải gọi cái này đầu tiên

        customerService = new CustomerService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Gán Model cho bảng jTable1
        jTable1.setModel(defaultTableModel);
        rowSorter = new javax.swing.table.TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(rowSorter);

        // Thêm các cột
        defaultTableModel.addColumn("Customer ID");
        defaultTableModel.addColumn("Fullname");
        defaultTableModel.addColumn("Number");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("Adress");
        defaultTableModel.addColumn("Type");

        // Đổ dữ liệu lên bảng
        setTableData(customerService.getAllUsers());
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                String query = txtSearch.getText();
                filter(query);
            }
        });
    }

    private void setTableData(List<Customer> customers) {
        defaultTableModel.setRowCount(0);

        for (Customer customer : customers) {
            defaultTableModel.addRow(new Object[]{
                customer.getCustomerId(),
                customer.getName(),
                customer.getPhone(),
                customer.getEmail(),
                customer.getAddress(),
                customer.getCustomerType()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(defaultTableModel);
        jTable1.setRowSorter(tr);

        if (query.trim().length() == 0) {
            tr.setRowFilter(null);
        } else {
            // Lọc không phân biệt chữ hoa chữ thường trên tất cả các cột
            tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CUSTOMER PANEL");

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        addButton.setText("ADD");
        addButton.addActionListener(this::addButtonActionPerformed);

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Search:");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(btnLogout)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(addButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Lấy vị trí dòng mà người dùng đang click chọn trên bảng
        // LƯU Ý: Đổi 'jTable1' thành tên cái bảng của bạn nhé (ví dụ: tblCustomer)
        int selectedRow = jTable1.getSelectedRow();

        // Nếu chưa chọn dòng nào mà bấm Xóa thì báo lỗi
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select one customer to delect!");
            return;
        }

        // 2. Hiện hộp thoại hỏi xác nhận cho an toàn
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Do you want to delete this customer? All the bill will be deleted too!",
                "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // 3. Lấy mã CustomerID (thường nằm ở Cột 0 của bảng)
                int customerId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

                // 4. Gọi Service để xóa dưới Database
                customerService.deleteCustomer(customerId);

                // 5. Báo thành công và Tự động làm mới bảng
                javax.swing.JOptionPane.showMessageDialog(this, "Delete succeed!");
                setTableData(customerService.getAllUsers()); // Nhớ đổi tên hàm này thành hàm vẽ bảng của bạn

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Ép kiểu về Frame để truyền vào JDialog
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) parentWindow;
        }

        // 3. Khởi tạo Dialog (truyền cha và true để bật tính năng Modal - khóa màn hình)
        AddCustomerFrame addDialog = new AddCustomerFrame(parentFrame, true);

        // 4. Hiển thị Dialog lên
        addDialog.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText(); // Lấy chữ người dùng vừa gõ

        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null); // Nếu xóa hết chữ, hiện lại toàn bộ bảng
        } else {
            // "(?i)" là "bí thuật" giúp tìm kiếm không phân biệt chữ hoa, chữ thường
            rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();

        // Kiểm tra xem người dùng đã chọn khách hàng nào chưa
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng trong bảng để cập nhật!", "Lỗi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Quan trọng: Vì bảng có dùng rowSorter (chức năng tìm kiếm), ta cần map đúng index từ View về Model
        int modelRow = jTable1.convertRowIndexToModel(row);

        // 2. Lấy dữ liệu từ DefaultTableModel dựa trên dòng đã chọn
        int id = (int) defaultTableModel.getValueAt(modelRow, 0);
        String name = (String) defaultTableModel.getValueAt(modelRow, 1);
        String phone = (String) defaultTableModel.getValueAt(modelRow, 2);
        String email = (String) defaultTableModel.getValueAt(modelRow, 3);
        String address = (String) defaultTableModel.getValueAt(modelRow, 4);
        String type = (String) defaultTableModel.getValueAt(modelRow, 5);

        // 3. Khởi tạo UpdateCustomerFrame (giống như cách bạn làm với AddCustomerFrame)
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) parentWindow;
        }

        UpdateCustomerFrame updateDialog = new UpdateCustomerFrame(parentFrame, true);

        // 4. Gọi hàm setCustomerData để truyền dữ liệu sang form Update
        updateDialog.setCustomerData(id, name, phone, email, address, type);

        // 5. Hiển thị Dialog lên
        updateDialog.setVisible(true);

        // 6. Làm mới lại bảng sau khi form Update đóng lại (để hiển thị dữ liệu mới vừa sửa)
        setTableData(customerService.getAllUsers());// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
// Hiển thị hộp thoại xác nhận
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất không?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 1. Đóng màn hình hiện tại
            this.dispose();

            // 2. Mở lại màn hình Login (Thay 'LoginFrame' bằng tên file đăng nhập của bạn)
            new LoginFrame().setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
