/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ThinkPad
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame1
     */
    public MainFrame() {
        initComponents();
    }

    private void showView(javax.swing.JFrame frame) {
        // 1. Xóa toàn bộ những gì đang hiện ở vùng bên phải (mainContent)
        mainContent.removeAll();

        // 2. Thiết lập BorderLayout để nội dung mới tràn đầy diện tích
        mainContent.setLayout(new java.awt.BorderLayout());

        // 3. LẤY RUỘT: Lấy ContentPane của JFrame con để add vào JPanel chính
        mainContent.add(frame.getContentPane(), java.awt.BorderLayout.CENTER);

        // 4. Vẽ lại giao diện
        mainContent.revalidate();
        mainContent.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        dashboardButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        waterMeterButton = new javax.swing.JButton();
        usageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestButton.setText("Request      ");
        requestButton.addActionListener(this::requestButtonActionPerformed);

        billButton.setText("Bill");
        billButton.addActionListener(this::billButtonActionPerformed);

        paymentButton.setText("Payment ");
        paymentButton.addActionListener(this::paymentButtonActionPerformed);

        btnLogout.setText("Log out");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnLogout)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnLogout)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        dashboardButton.setText("Dashboard    ");
        dashboardButton.addActionListener(this::dashboardButtonActionPerformed);

        customerButton.setText("Customer");
        customerButton.addActionListener(this::customerButtonActionPerformed);

        waterMeterButton.setText("Water Meter ");
        waterMeterButton.addActionListener(this::waterMeterButtonActionPerformed);

        usageButton.setText("Usage");
        usageButton.addActionListener(this::usageButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waterMeterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(dashboardButton)
                        .addGap(30, 30, 30)
                        .addComponent(customerButton)
                        .addGap(23, 23, 23)
                        .addComponent(waterMeterButton)
                        .addGap(18, 18, 18)
                        .addComponent(usageButton)
                        .addGap(29, 29, 29)
                        .addComponent(billButton)
                        .addGap(18, 18, 18)
                        .addComponent(paymentButton)
                        .addGap(18, 18, 18)
                        .addComponent(requestButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(mainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed
        // TODO add your handling code here:
        showView(new RequestFrame());
    }//GEN-LAST:event_requestButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
        showView(new BillFrame());
    }//GEN-LAST:event_billButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
        showView(new PaymentFrame());
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // TODO add your handling code here:
        showView(new DashBoardFrame());
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        showView(new CustomerFrame());
    }//GEN-LAST:event_customerButtonActionPerformed

    private void waterMeterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterMeterButtonActionPerformed
        // TODO add your handling code here:
        showView(new WaterMeterFrame());

    }//GEN-LAST:event_waterMeterButtonActionPerformed

    private void usageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usageButtonActionPerformed
        // TODO add your handling code here:
        showView(new UsageFrame());
    }//GEN-LAST:event_usageButtonActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Hiển thị hộp thoại xác nhận
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất không?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 1. Đóng màn hình hiện tại
            this.dispose();

            // 2. Mở lại màn hình Login (Thay 'LoginFrame' bằng tên file đăng nhập của bạn)
            new LoginFrame().setVisible(true);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billButton;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JPanel mainContent;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton requestButton;
    private javax.swing.JButton usageButton;
    private javax.swing.JButton waterMeterButton;
    // End of variables declaration//GEN-END:variables
}
